### ISSUE TITLE
End of line problem

### ISSUE THREAD

**Issue by german-bortoli** [rudimeier/bash_ini_parser#4] opened 2013-03-02 02:33 UTC
When I put one variable into a ini file at the end of file, it doesn't read correctly.

**Comment by rudimeier** [comment] 2013-03-05 08:45
Thanks,
more precisely the problem is a missing newline at the end of ini file.
Note that in general any text (or .ini) file should end with a line feed because many text processing tools could have problems if it's missing. For example even "wc -l" would not count such a last line.

Fixed in daf1fd3c

**Closed as completed by rudimeier** 2013-03-05 08:45 UTC
